import "./globals.css";
import RQProvider from "./components/RQProvider";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="bg-gray-100">
				<RQProvider>{children}</RQProvider>
			</body>
		</html>
	);
}
